name = "CompileTimePreferences"
uuid = "028f7cdb-0e28-4ceb-8483-61792cdc2850"
authors = ["Elliot Saba <staticfloat@gmail.com>"]
version = "0.1.0"

[deps]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"

[targets]
test = ["Test", "SHA"]
